import Head from "next/head";

export default function PodcastDetails() {
  return (
    <>
      <Head>
        <title>PodcastDetails</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>PodcastDetails</main>
    </>
  );
}
